#!/usr/bin/env node
// Copyright (c) 2026 Digistore24 Inc, St. Petersburg, USA
// SPDX-License-Identifier: MIT
//
// read-guard.mjs — the rule in CLAUDE.md → *Reading the tree*, enforced.
//
// A `PreToolUse` hook for Claude Code (`.claude/settings.json`, generated by
// `scripts/dev/agent-configs.mjs`): a `Read` with no `offset`/`limit` on a file
// longer than MAX_LINES, or a Bash `cat` of one that is not piped into
// `head`/`sed`/`grep`, is refused — with the line count and the two ways that
// work. Everything else passes, and so does everything this cannot judge (a
// file that does not exist, a path it cannot read, a tool it does not know):
// the guard errs towards letting a call through.
//
// ── Why a hook and not the sentence that already exists ────────────────────
//
// "read directly — in a RANGE rather than whole, and never through `cat`" has
// stood in CLAUDE.md for months. Measured on 2026-09-03 over two archived
// build sessions (`2026-08-11T1712-gated-tool`, `2026-08-01T2226-quiz`): 13 and
// 4 whole reads of files over 200 lines, 51,000 tokens in the first — each one
// re-read by every one of the ~150 requests that followed, about a fifth of
// the session. A sentence that is measured 13 times ignored is not a lever; a
// refusal the model reads as the tool's own answer is.
//
// ── The threshold, stated ──────────────────────────────────────────────────
//
// 200 lines. Read off the same two transcripts: at 200 the guard refuses 13
// calls in the first run and lets 6 ranged reads and 21 short files through;
// at 150 it would refuse one more, at 300 only four. Two hundred is also about
// where a page of this template lands (`account/page.tsx` 409, `layout.tsx`
// 247, `app-shell.tsx` 250) — the files a session reads to copy a shape it
// could grep. `docs/api-map.md` (494 lines) is over it on purpose: its own
// header says to read a section.
//
// ── What it does NOT do ────────────────────────────────────────────────────
//
// It does not count re-reads, does not know Codex, OpenCode or Antigravity
// (none of them runs hooks — the sentence in CLAUDE.md is still the rule
// there), and it never blocks a write. Whoever finds it in the way reads a
// range; nobody removes it — `docs/troubleshooting.md` → *The read guard said
// no*.
//
// Pure decision in `decide()`, so `scripts/dev/hooks/read-guard.test.ts` can hold
// it to fixtures, and the factory can replay a whole archived transcript
// through it. The CLI reads the hook's JSON from stdin and prints a decision or
// nothing.

import { existsSync, readFileSync, statSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const MAX_LINES = 200;

/** Utilities that stand between a `cat` and the context — a `cat … | head` is a range. */
const NARROWERS = /^\s*(head|tail|sed|grep|egrep|rg|awk|wc|jq|cut|sort|uniq|less|more)\b/;

/** Lines of a file, the portable way (`wc -l` is not one) — null when unreadable. */
export function countLines(path) {
  try {
    if (!existsSync(path) || !statSync(path).isFile()) return null;
    return readFileSync(path, "utf8").split(/\r?\n/).length;
  } catch {
    return null;
  }
}

/**
 * The `cat` calls in a shell string, each with its file arguments and whether
 * something narrows it afterwards. Split on the operators that end a command;
 * a `|` ends one too, and what follows it decides `narrowed`.
 */
export function catCalls(command) {
  const out = [];
  // A segment followed by `|` is narrowed when the next segment starts with a
  // narrower; `;`, `&&`, `||` and a newline end a command without narrowing.
  for (const line of String(command).split(/\r?\n|;|&&|\|\|/)) {
    const parts = line.split("|");
    for (let i = 0; i < parts.length; i += 1) {
      const words = parts[i].trim().split(/\s+/).filter(Boolean);
      // `cd x && cat y` is split already; `sudo cat`, `time cat` are not — a
      // `cat` anywhere but first is somebody else's argument.
      if (words[0] !== "cat") continue;
      // Flags are not files, and neither is a redirection's target: `cat > x`
      // and `cat a > x` WRITE x. A bare operator (`>`, `>>`, `<<`, `2>`) takes
      // the next word with it; a glued one (`>x`, `2>/dev/null`) is one word.
      const files = [];
      for (let w = 1; w < words.length; w += 1) {
        const word = words[w];
        if (/^\d*[<>]+-?$/.test(word)) { w += 1; continue; }
        if (/^\d*[<>]/.test(word) || word.startsWith("-")) continue;
        files.push(word);
      }
      const narrowed = i + 1 < parts.length && NARROWERS.test(parts[i + 1]);
      out.push({ files, narrowed });
    }
  }
  return out;
}

/**
 * The decision, pure: `null` to allow, or the reason to refuse.
 *
 * `lineCount(path)` is injected so a test can replay an archived transcript
 * whose files no longer exist; the CLI passes `countLines`. The options are
 * typed here because `tsc --noEmit` reads the `.test.ts` beside this file and
 * infers a JS destructuring without a default (`cwd`) as "no such property" —
 * measured by the dry field run, where vitest was green and typecheck was not.
 *
 * @param {{ tool_name?: string, tool_input?: Record<string, unknown> } | null} input
 * @param {{ cwd?: string, lineCount?: (path: string) => number | null, maxLines?: number }} [options]
 * @returns {string | null}
 */
export function decide(input, { cwd, lineCount = countLines, maxLines = MAX_LINES } = {}) {
  const name = input?.tool_name;
  const tool = input?.tool_input ?? {};
  const at = (p) => (isAbsolute(p) ? p : resolve(cwd ?? process.cwd(), p));
  const refuse = (path, lines, how) =>
    `${path} has ${lines} lines. Whole-file reads stay in your context for every request after, ` +
    `so read a RANGE (${how}) or grep for what you need — CLAUDE.md → "Reading the tree". ` +
    `A doc that long has a Contents block or sections: read the section.`;

  if (name === "Read") {
    const path = tool.file_path;
    if (typeof path !== "string" || path === "") return null;
    if (tool.offset !== undefined || tool.limit !== undefined) return null;
    const lines = lineCount(at(path));
    if (lines === null || lines <= maxLines) return null;
    return refuse(path, lines, "offset + limit");
  }

  if (name === "Bash") {
    for (const call of catCalls(tool.command ?? "")) {
      if (call.narrowed) continue;
      for (const file of call.files) {
        const lines = lineCount(at(file));
        if (lines !== null && lines > maxLines) return refuse(file, lines, "sed -n 'a,bp'");
      }
    }
    return null;
  }

  return null;
}

// ── CLI: the hook itself ─────────────────────────────────────────────────────

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  let raw = "";
  process.stdin.setEncoding("utf8");
  process.stdin.on("data", (chunk) => { raw += chunk; });
  process.stdin.on("end", () => {
    let input = null;
    try { input = JSON.parse(raw); } catch { input = null; }
    const reason = input ? decide(input, { cwd: input.cwd }) : null;
    if (reason !== null) {
      process.stdout.write(
        `${JSON.stringify({
          hookSpecificOutput: {
            hookEventName: "PreToolUse",
            permissionDecision: "deny",
            permissionDecisionReason: reason,
          },
        })}\n`,
      );
    }
    process.exit(0);
  });
}

// Keep the entry usable as a module from the factory's replay test as well.
export const HOOK_PATH = fileURLToPath(import.meta.url);
