// Copyright (c) 2026 Digistore24 Inc, St. Petersburg, USA
// SPDX-License-Identifier: MIT

// The stub that makes a skill findable outside .claude/skills/.
//
// Two programs read the real tree (Claude Code, OpenCode) and two look under
// .agents/skills/ instead (Codex, Antigravity). Rather than keep the skills twice,
// the second path gets a stub per skill: the frontmatter copied verbatim, so
// discovery and matching behave exactly as for the real file, and a body that
// says where the real file is.
//
// Pure on purpose — text in, text out, no fs. Two very different callers share
// it and neither may drift from the other:
//
//   scripts/agent-skills-stamp.mjs   in the factory, writes the stubs that ship
//   scripts/dev/agent-setup.mjs      in a customer's app, puts them back after
//                                    they were pruned for another program
//
// `requires:` travels along. update-plan.mjs uses it to refuse a skill whose
// code is newer than the app it would land in, and a stub that slipped past
// that check would be a signpost to a file the update just declined to write.

/**
 * The frontmatter fields a stub carries over.
 * @throws when the file has no frontmatter, or name/description are missing.
 */
export function skillFrontmatter(text, skill) {
  const block = /^---\n([\s\S]*?)\n---/.exec(text);
  if (!block) throw new Error(`${skill}: no frontmatter`);

  const field = (key) => {
    const hit = new RegExp(`^${key}:[ \\t]*(.+)$`, "m").exec(block[1]);
    return hit ? hit[1].trim() : null;
  };

  const name = field("name");
  const description = field("description");
  if (!name || !description) throw new Error(`${skill}: name and description are required`);
  if (name !== skill) throw new Error(`${skill}: frontmatter says name: ${name}`);

  return { name, description, requires: field("requires") };
}

/** The complete text of `.agents/skills/<skill>/SKILL.md`. */
export function stubFor(text, skill) {
  const { name, description, requires } = skillFrontmatter(text, skill);

  const head = ["---", `name: ${name}`, `description: ${description}`];
  if (requires) head.push(`requires: ${requires}`);
  head.push("---");

  return `${head.join("\n")}
<!-- Generated from .claude/skills/${name}/SKILL.md — do not edit this file. -->

Read \`.claude/skills/${name}/SKILL.md\` in full and follow it exactly.

That is the real skill. This file only makes it discoverable in programs that
look for skills under \`.agents/skills/\` instead.
`;
}
